### ISSUE TITLE
Allow to configure ports for masquerade

### ISSUE THREAD

**Issue by SchSeba** [kubevirt/web-ui#376]
When we create a VM/VMI with a masquerade interface we need to configure the ports we want to forward into the vm.

In the yaml it looks like this:
```yaml
interfaces:
      - masquerade: {}
        name: testmasquerade
        ports:
        - name: http
          port: 80
          protocol: TCP
```

This should be reflected into the UI also.
